"""add_profile_food_preferences

Revision ID: bf2c42dbc8ab
Revises: 001
Create Date: 2026-03-01 11:20:23.701680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf2c42dbc8ab'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('meals_per_day', sa.Integer(), nullable=True))
    op.add_column('user_profiles', sa.Column('food_allergies', sa.Text(), nullable=True))
    op.add_column('user_profiles', sa.Column('disliked_foods', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'disliked_foods')
    op.drop_column('user_profiles', 'food_allergies')
    op.drop_column('user_profiles', 'meals_per_day')
    # ### end Alembic commands ###
