"""add_custom_health_notes

Revision ID: c879e0b3b1c5
Revises: bf2c42dbc8ab
Create Date: 2026-03-01 15:06:21.288415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c879e0b3b1c5'
down_revision: Union[str, None] = 'bf2c42dbc8ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('custom_health_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'custom_health_notes')
    # ### end Alembic commands ###
