"""Seed data for food items.

Nutritional values per 100g. Sources: USDA FoodData Central, Russian
nutritional reference tables. Values are approximate averages for raw/uncooked
products unless otherwise noted.
"""

FOODS = [
    # ========================================================================
    # MEAT & POULTRY (Мясо и птица)
    # ========================================================================
    {
        "name": "Chicken Breast",
        "name_ru": "Куриная грудка",
        "calories_per_100g": 165,
        "protein_per_100g": 31.0,
        "fat_per_100g": 3.6,
        "carbs_per_100g": 0.0,
        "fiber_per_100g": 0.0,
        "category": "meat",
        "serving_size_g": 150,
    },
    {
        "name": "Chicken Thigh",
        "name_ru": "Куриное бедро",
        "calories_per_100g": 209,
        "protein_per_100g": 26.0,
        "fat_per_100g": 10.9,
        "carbs_per_100g": 0.0,
        "fiber_per_100g": 0.0,
        "category": "meat",
        "serving_size_g": 130,
    },
    {
        "name": "Turkey Breast",
        "name_ru": "Грудка индейки",
        "calories_per_100g": 135,
        "protein_per_100g": 30.0,
        "fat_per_100g": 1.0,
        "carbs_per_100g": 0.0,
        "fiber_per_100g": 0.0,
        "category": "meat",
        "serving_size_g": 150,
    },
    {
        "name": "Beef Sirloin",
        "name_ru": "Говяжья вырезка",
        "calories_per_100g": 199,
        "protein_per_100g": 27.0,
        "fat_per_100g": 10.0,
        "carbs_per_100g": 0.0,
        "fiber_per_100g": 0.0,
        "category": "meat",
        "serving_size_g": 150,
    },
    {
        "name": "Ground Beef (lean)",
        "name_ru": "Говяжий фарш (нежирный)",
        "calories_per_100g": 176,
        "protein_per_100g": 25.0,
        "fat_per_100g": 8.0,
        "carbs_per_100g": 0.0,
        "fiber_per_100g": 0.0,
        "category": "meat",
        "serving_size_g": 120,
    },
    {
        "name": "Pork Loin",
        "name_ru": "Свиная корейка",
        "calories_per_100g": 196,
        "protein_per_100g": 27.0,
        "fat_per_100g": 9.0,
        "carbs_per_100g": 0.0,
        "fiber_per_100g": 0.0,
        "category": "meat",
        "serving_size_g": 150,
    },
    {
        "name": "Pork Tenderloin",
        "name_ru": "Свиная вырезка",
        "calories_per_100g": 143,
        "protein_per_100g": 26.0,
        "fat_per_100g": 3.5,
        "carbs_per_100g": 0.0,
        "fiber_per_100g": 0.0,
        "category": "meat",
        "serving_size_g": 150,
    },
    {
        "name": "Lamb Leg",
        "name_ru": "Баранья нога",
        "calories_per_100g": 230,
        "protein_per_100g": 25.0,
        "fat_per_100g": 14.0,
        "carbs_per_100g": 0.0,
        "fiber_per_100g": 0.0,
        "category": "meat",
        "serving_size_g": 150,
    },

    # ========================================================================
    # FISH & SEAFOOD (Рыба и морепродукты)
    # ========================================================================
    {
        "name": "Salmon",
        "name_ru": "Лосось",
        "calories_per_100g": 208,
        "protein_per_100g": 20.0,
        "fat_per_100g": 13.0,
        "carbs_per_100g": 0.0,
        "fiber_per_100g": 0.0,
        "category": "fish",
        "serving_size_g": 150,
    },
    {
        "name": "Tuna (canned in water)",
        "name_ru": "Тунец (консервированный в воде)",
        "calories_per_100g": 116,
        "protein_per_100g": 25.5,
        "fat_per_100g": 1.0,
        "carbs_per_100g": 0.0,
        "fiber_per_100g": 0.0,
        "category": "fish",
        "serving_size_g": 100,
    },
    {
        "name": "Cod",
        "name_ru": "Треска",
        "calories_per_100g": 82,
        "protein_per_100g": 18.0,
        "fat_per_100g": 0.7,
        "carbs_per_100g": 0.0,
        "fiber_per_100g": 0.0,
        "category": "fish",
        "serving_size_g": 150,
    },
    {
        "name": "Shrimp",
        "name_ru": "Креветки",
        "calories_per_100g": 99,
        "protein_per_100g": 24.0,
        "fat_per_100g": 0.3,
        "carbs_per_100g": 0.2,
        "fiber_per_100g": 0.0,
        "category": "fish",
        "serving_size_g": 100,
    },
    {
        "name": "Tilapia",
        "name_ru": "Тилапия",
        "calories_per_100g": 96,
        "protein_per_100g": 20.0,
        "fat_per_100g": 1.7,
        "carbs_per_100g": 0.0,
        "fiber_per_100g": 0.0,
        "category": "fish",
        "serving_size_g": 150,
    },
    {
        "name": "Mackerel",
        "name_ru": "Скумбрия",
        "calories_per_100g": 205,
        "protein_per_100g": 19.0,
        "fat_per_100g": 13.9,
        "carbs_per_100g": 0.0,
        "fiber_per_100g": 0.0,
        "category": "fish",
        "serving_size_g": 150,
    },
    {
        "name": "Herring",
        "name_ru": "Сельдь",
        "calories_per_100g": 158,
        "protein_per_100g": 18.0,
        "fat_per_100g": 9.0,
        "carbs_per_100g": 0.0,
        "fiber_per_100g": 0.0,
        "category": "fish",
        "serving_size_g": 100,
    },

    # ========================================================================
    # EGGS & DAIRY (Яйца и молочные продукты)
    # ========================================================================
    {
        "name": "Egg (whole)",
        "name_ru": "Яйцо куриное",
        "calories_per_100g": 155,
        "protein_per_100g": 13.0,
        "fat_per_100g": 11.0,
        "carbs_per_100g": 1.1,
        "fiber_per_100g": 0.0,
        "category": "dairy",
        "serving_size_g": 50,
    },
    {
        "name": "Egg White",
        "name_ru": "Яичный белок",
        "calories_per_100g": 52,
        "protein_per_100g": 11.0,
        "fat_per_100g": 0.2,
        "carbs_per_100g": 0.7,
        "fiber_per_100g": 0.0,
        "category": "dairy",
        "serving_size_g": 33,
    },
    {
        "name": "Cottage Cheese (5%)",
        "name_ru": "Творог (5%)",
        "calories_per_100g": 121,
        "protein_per_100g": 17.0,
        "fat_per_100g": 5.0,
        "carbs_per_100g": 1.8,
        "fiber_per_100g": 0.0,
        "category": "dairy",
        "serving_size_g": 150,
    },
    {
        "name": "Cottage Cheese (0%)",
        "name_ru": "Творог обезжиренный",
        "calories_per_100g": 72,
        "protein_per_100g": 18.0,
        "fat_per_100g": 0.1,
        "carbs_per_100g": 1.8,
        "fiber_per_100g": 0.0,
        "category": "dairy",
        "serving_size_g": 150,
    },
    {
        "name": "Greek Yogurt",
        "name_ru": "Греческий йогурт",
        "calories_per_100g": 97,
        "protein_per_100g": 9.0,
        "fat_per_100g": 5.0,
        "carbs_per_100g": 3.6,
        "fiber_per_100g": 0.0,
        "category": "dairy",
        "serving_size_g": 170,
    },
    {
        "name": "Milk (2.5%)",
        "name_ru": "Молоко (2,5%)",
        "calories_per_100g": 52,
        "protein_per_100g": 2.8,
        "fat_per_100g": 2.5,
        "carbs_per_100g": 4.7,
        "fiber_per_100g": 0.0,
        "category": "dairy",
        "serving_size_g": 250,
    },
    {
        "name": "Cheese (hard, 45%)",
        "name_ru": "Сыр твёрдый (45%)",
        "calories_per_100g": 356,
        "protein_per_100g": 25.0,
        "fat_per_100g": 28.0,
        "carbs_per_100g": 0.0,
        "fiber_per_100g": 0.0,
        "category": "dairy",
        "serving_size_g": 30,
    },
    {
        "name": "Mozzarella",
        "name_ru": "Моцарелла",
        "calories_per_100g": 280,
        "protein_per_100g": 22.0,
        "fat_per_100g": 21.0,
        "carbs_per_100g": 2.2,
        "fiber_per_100g": 0.0,
        "category": "dairy",
        "serving_size_g": 50,
    },
    {
        "name": "Butter",
        "name_ru": "Сливочное масло",
        "calories_per_100g": 717,
        "protein_per_100g": 0.9,
        "fat_per_100g": 81.0,
        "carbs_per_100g": 0.1,
        "fiber_per_100g": 0.0,
        "category": "dairy",
        "serving_size_g": 10,
    },
    {
        "name": "Cream (20%)",
        "name_ru": "Сливки (20%)",
        "calories_per_100g": 205,
        "protein_per_100g": 2.8,
        "fat_per_100g": 20.0,
        "carbs_per_100g": 3.7,
        "fiber_per_100g": 0.0,
        "category": "dairy",
        "serving_size_g": 30,
    },
    {
        "name": "Kefir (1%)",
        "name_ru": "Кефир (1%)",
        "calories_per_100g": 40,
        "protein_per_100g": 3.0,
        "fat_per_100g": 1.0,
        "carbs_per_100g": 4.0,
        "fiber_per_100g": 0.0,
        "category": "dairy",
        "serving_size_g": 250,
    },
    {
        "name": "Sour Cream (15%)",
        "name_ru": "Сметана (15%)",
        "calories_per_100g": 162,
        "protein_per_100g": 2.6,
        "fat_per_100g": 15.0,
        "carbs_per_100g": 3.6,
        "fiber_per_100g": 0.0,
        "category": "dairy",
        "serving_size_g": 30,
    },

    # ========================================================================
    # GRAINS & CEREALS (Крупы и злаки)
    # ========================================================================
    {
        "name": "White Rice (dry)",
        "name_ru": "Белый рис (сухой)",
        "calories_per_100g": 365,
        "protein_per_100g": 7.0,
        "fat_per_100g": 0.7,
        "carbs_per_100g": 79.0,
        "fiber_per_100g": 1.3,
        "category": "grains",
        "serving_size_g": 80,
    },
    {
        "name": "Brown Rice (dry)",
        "name_ru": "Бурый рис (сухой)",
        "calories_per_100g": 370,
        "protein_per_100g": 7.9,
        "fat_per_100g": 2.9,
        "carbs_per_100g": 74.0,
        "fiber_per_100g": 3.5,
        "category": "grains",
        "serving_size_g": 80,
    },
    {
        "name": "Buckwheat (dry)",
        "name_ru": "Гречка (сухая)",
        "calories_per_100g": 343,
        "protein_per_100g": 13.3,
        "fat_per_100g": 3.4,
        "carbs_per_100g": 68.0,
        "fiber_per_100g": 10.0,
        "category": "grains",
        "serving_size_g": 80,
    },
    {
        "name": "Oatmeal (dry)",
        "name_ru": "Овсянка (сухая)",
        "calories_per_100g": 389,
        "protein_per_100g": 16.9,
        "fat_per_100g": 6.9,
        "carbs_per_100g": 66.0,
        "fiber_per_100g": 10.6,
        "category": "grains",
        "serving_size_g": 50,
    },
    {
        "name": "Pasta (dry)",
        "name_ru": "Макароны (сухие)",
        "calories_per_100g": 371,
        "protein_per_100g": 13.0,
        "fat_per_100g": 1.5,
        "carbs_per_100g": 75.0,
        "fiber_per_100g": 3.2,
        "category": "grains",
        "serving_size_g": 80,
    },
    {
        "name": "White Bread",
        "name_ru": "Белый хлеб",
        "calories_per_100g": 265,
        "protein_per_100g": 9.0,
        "fat_per_100g": 3.2,
        "carbs_per_100g": 49.0,
        "fiber_per_100g": 2.7,
        "category": "grains",
        "serving_size_g": 30,
    },
    {
        "name": "Rye Bread",
        "name_ru": "Ржаной хлеб",
        "calories_per_100g": 259,
        "protein_per_100g": 8.5,
        "fat_per_100g": 3.3,
        "carbs_per_100g": 48.0,
        "fiber_per_100g": 5.8,
        "category": "grains",
        "serving_size_g": 30,
    },
    {
        "name": "Quinoa (dry)",
        "name_ru": "Киноа (сухая)",
        "calories_per_100g": 368,
        "protein_per_100g": 14.1,
        "fat_per_100g": 6.1,
        "carbs_per_100g": 64.0,
        "fiber_per_100g": 7.0,
        "category": "grains",
        "serving_size_g": 80,
    },
    {
        "name": "Couscous (dry)",
        "name_ru": "Кускус (сухой)",
        "calories_per_100g": 376,
        "protein_per_100g": 12.8,
        "fat_per_100g": 0.6,
        "carbs_per_100g": 77.0,
        "fiber_per_100g": 5.0,
        "category": "grains",
        "serving_size_g": 80,
    },
    {
        "name": "Rice Cakes",
        "name_ru": "Рисовые хлебцы",
        "calories_per_100g": 387,
        "protein_per_100g": 8.0,
        "fat_per_100g": 2.8,
        "carbs_per_100g": 81.0,
        "fiber_per_100g": 4.2,
        "category": "grains",
        "serving_size_g": 10,
    },

    # ========================================================================
    # VEGETABLES (Овощи)
    # ========================================================================
    {
        "name": "Broccoli",
        "name_ru": "Брокколи",
        "calories_per_100g": 34,
        "protein_per_100g": 2.8,
        "fat_per_100g": 0.4,
        "carbs_per_100g": 7.0,
        "fiber_per_100g": 2.6,
        "category": "vegetables",
        "serving_size_g": 150,
    },
    {
        "name": "Spinach",
        "name_ru": "Шпинат",
        "calories_per_100g": 23,
        "protein_per_100g": 2.9,
        "fat_per_100g": 0.4,
        "carbs_per_100g": 3.6,
        "fiber_per_100g": 2.2,
        "category": "vegetables",
        "serving_size_g": 100,
    },
    {
        "name": "Tomato",
        "name_ru": "Помидор",
        "calories_per_100g": 18,
        "protein_per_100g": 0.9,
        "fat_per_100g": 0.2,
        "carbs_per_100g": 3.9,
        "fiber_per_100g": 1.2,
        "category": "vegetables",
        "serving_size_g": 150,
    },
    {
        "name": "Cucumber",
        "name_ru": "Огурец",
        "calories_per_100g": 15,
        "protein_per_100g": 0.7,
        "fat_per_100g": 0.1,
        "carbs_per_100g": 3.6,
        "fiber_per_100g": 0.5,
        "category": "vegetables",
        "serving_size_g": 150,
    },
    {
        "name": "Carrot",
        "name_ru": "Морковь",
        "calories_per_100g": 41,
        "protein_per_100g": 0.9,
        "fat_per_100g": 0.2,
        "carbs_per_100g": 10.0,
        "fiber_per_100g": 2.8,
        "category": "vegetables",
        "serving_size_g": 100,
    },
    {
        "name": "Potato",
        "name_ru": "Картофель",
        "calories_per_100g": 77,
        "protein_per_100g": 2.0,
        "fat_per_100g": 0.1,
        "carbs_per_100g": 17.5,
        "fiber_per_100g": 2.2,
        "category": "vegetables",
        "serving_size_g": 200,
    },
    {
        "name": "Sweet Potato",
        "name_ru": "Батат",
        "calories_per_100g": 86,
        "protein_per_100g": 1.6,
        "fat_per_100g": 0.1,
        "carbs_per_100g": 20.0,
        "fiber_per_100g": 3.0,
        "category": "vegetables",
        "serving_size_g": 200,
    },
    {
        "name": "Bell Pepper",
        "name_ru": "Болгарский перец",
        "calories_per_100g": 27,
        "protein_per_100g": 1.0,
        "fat_per_100g": 0.3,
        "carbs_per_100g": 6.0,
        "fiber_per_100g": 2.1,
        "category": "vegetables",
        "serving_size_g": 150,
    },
    {
        "name": "Cabbage",
        "name_ru": "Капуста белокочанная",
        "calories_per_100g": 25,
        "protein_per_100g": 1.3,
        "fat_per_100g": 0.1,
        "carbs_per_100g": 5.8,
        "fiber_per_100g": 2.5,
        "category": "vegetables",
        "serving_size_g": 150,
    },
    {
        "name": "Onion",
        "name_ru": "Лук репчатый",
        "calories_per_100g": 40,
        "protein_per_100g": 1.1,
        "fat_per_100g": 0.1,
        "carbs_per_100g": 9.3,
        "fiber_per_100g": 1.7,
        "category": "vegetables",
        "serving_size_g": 80,
    },
    {
        "name": "Garlic",
        "name_ru": "Чеснок",
        "calories_per_100g": 149,
        "protein_per_100g": 6.4,
        "fat_per_100g": 0.5,
        "carbs_per_100g": 33.0,
        "fiber_per_100g": 2.1,
        "category": "vegetables",
        "serving_size_g": 5,
    },
    {
        "name": "Lettuce (Iceberg)",
        "name_ru": "Салат айсберг",
        "calories_per_100g": 14,
        "protein_per_100g": 0.9,
        "fat_per_100g": 0.1,
        "carbs_per_100g": 3.0,
        "fiber_per_100g": 1.2,
        "category": "vegetables",
        "serving_size_g": 100,
    },
    {
        "name": "Avocado",
        "name_ru": "Авокадо",
        "calories_per_100g": 160,
        "protein_per_100g": 2.0,
        "fat_per_100g": 14.7,
        "carbs_per_100g": 8.5,
        "fiber_per_100g": 6.7,
        "category": "vegetables",
        "serving_size_g": 100,
    },
    {
        "name": "Zucchini",
        "name_ru": "Кабачок",
        "calories_per_100g": 17,
        "protein_per_100g": 1.2,
        "fat_per_100g": 0.3,
        "carbs_per_100g": 3.1,
        "fiber_per_100g": 1.0,
        "category": "vegetables",
        "serving_size_g": 200,
    },
    {
        "name": "Eggplant",
        "name_ru": "Баклажан",
        "calories_per_100g": 25,
        "protein_per_100g": 1.0,
        "fat_per_100g": 0.2,
        "carbs_per_100g": 6.0,
        "fiber_per_100g": 3.0,
        "category": "vegetables",
        "serving_size_g": 200,
    },
    {
        "name": "Cauliflower",
        "name_ru": "Цветная капуста",
        "calories_per_100g": 25,
        "protein_per_100g": 1.9,
        "fat_per_100g": 0.3,
        "carbs_per_100g": 5.0,
        "fiber_per_100g": 2.0,
        "category": "vegetables",
        "serving_size_g": 150,
    },
    {
        "name": "Green Beans",
        "name_ru": "Стручковая фасоль",
        "calories_per_100g": 31,
        "protein_per_100g": 1.8,
        "fat_per_100g": 0.1,
        "carbs_per_100g": 7.0,
        "fiber_per_100g": 3.4,
        "category": "vegetables",
        "serving_size_g": 100,
    },
    {
        "name": "Corn (sweet)",
        "name_ru": "Кукуруза сладкая",
        "calories_per_100g": 86,
        "protein_per_100g": 3.2,
        "fat_per_100g": 1.2,
        "carbs_per_100g": 19.0,
        "fiber_per_100g": 2.7,
        "category": "vegetables",
        "serving_size_g": 150,
    },
    {
        "name": "Beetroot",
        "name_ru": "Свёкла",
        "calories_per_100g": 43,
        "protein_per_100g": 1.6,
        "fat_per_100g": 0.2,
        "carbs_per_100g": 9.6,
        "fiber_per_100g": 2.8,
        "category": "vegetables",
        "serving_size_g": 150,
    },
    {
        "name": "Mushrooms (champignon)",
        "name_ru": "Шампиньоны",
        "calories_per_100g": 22,
        "protein_per_100g": 3.1,
        "fat_per_100g": 0.3,
        "carbs_per_100g": 3.3,
        "fiber_per_100g": 1.0,
        "category": "vegetables",
        "serving_size_g": 100,
    },

    # ========================================================================
    # FRUITS (Фрукты и ягоды)
    # ========================================================================
    {
        "name": "Banana",
        "name_ru": "Банан",
        "calories_per_100g": 89,
        "protein_per_100g": 1.1,
        "fat_per_100g": 0.3,
        "carbs_per_100g": 23.0,
        "fiber_per_100g": 2.6,
        "category": "fruits",
        "serving_size_g": 120,
    },
    {
        "name": "Apple",
        "name_ru": "Яблоко",
        "calories_per_100g": 52,
        "protein_per_100g": 0.3,
        "fat_per_100g": 0.2,
        "carbs_per_100g": 14.0,
        "fiber_per_100g": 2.4,
        "category": "fruits",
        "serving_size_g": 180,
    },
    {
        "name": "Orange",
        "name_ru": "Апельсин",
        "calories_per_100g": 47,
        "protein_per_100g": 0.9,
        "fat_per_100g": 0.1,
        "carbs_per_100g": 12.0,
        "fiber_per_100g": 2.4,
        "category": "fruits",
        "serving_size_g": 180,
    },
    {
        "name": "Strawberry",
        "name_ru": "Клубника",
        "calories_per_100g": 32,
        "protein_per_100g": 0.7,
        "fat_per_100g": 0.3,
        "carbs_per_100g": 7.7,
        "fiber_per_100g": 2.0,
        "category": "fruits",
        "serving_size_g": 150,
    },
    {
        "name": "Blueberry",
        "name_ru": "Голубика",
        "calories_per_100g": 57,
        "protein_per_100g": 0.7,
        "fat_per_100g": 0.3,
        "carbs_per_100g": 14.5,
        "fiber_per_100g": 2.4,
        "category": "fruits",
        "serving_size_g": 100,
    },
    {
        "name": "Watermelon",
        "name_ru": "Арбуз",
        "calories_per_100g": 30,
        "protein_per_100g": 0.6,
        "fat_per_100g": 0.2,
        "carbs_per_100g": 7.6,
        "fiber_per_100g": 0.4,
        "category": "fruits",
        "serving_size_g": 300,
    },
    {
        "name": "Grape",
        "name_ru": "Виноград",
        "calories_per_100g": 69,
        "protein_per_100g": 0.7,
        "fat_per_100g": 0.2,
        "carbs_per_100g": 18.0,
        "fiber_per_100g": 0.9,
        "category": "fruits",
        "serving_size_g": 100,
    },
    {
        "name": "Mango",
        "name_ru": "Манго",
        "calories_per_100g": 60,
        "protein_per_100g": 0.8,
        "fat_per_100g": 0.4,
        "carbs_per_100g": 15.0,
        "fiber_per_100g": 1.6,
        "category": "fruits",
        "serving_size_g": 200,
    },
    {
        "name": "Kiwi",
        "name_ru": "Киви",
        "calories_per_100g": 61,
        "protein_per_100g": 1.1,
        "fat_per_100g": 0.5,
        "carbs_per_100g": 15.0,
        "fiber_per_100g": 3.0,
        "category": "fruits",
        "serving_size_g": 75,
    },
    {
        "name": "Lemon",
        "name_ru": "Лимон",
        "calories_per_100g": 29,
        "protein_per_100g": 1.1,
        "fat_per_100g": 0.3,
        "carbs_per_100g": 9.3,
        "fiber_per_100g": 2.8,
        "category": "fruits",
        "serving_size_g": 50,
    },
    {
        "name": "Pear",
        "name_ru": "Груша",
        "calories_per_100g": 57,
        "protein_per_100g": 0.4,
        "fat_per_100g": 0.1,
        "carbs_per_100g": 15.0,
        "fiber_per_100g": 3.1,
        "category": "fruits",
        "serving_size_g": 180,
    },
    {
        "name": "Pineapple",
        "name_ru": "Ананас",
        "calories_per_100g": 50,
        "protein_per_100g": 0.5,
        "fat_per_100g": 0.1,
        "carbs_per_100g": 13.0,
        "fiber_per_100g": 1.4,
        "category": "fruits",
        "serving_size_g": 150,
    },
    {
        "name": "Raspberry",
        "name_ru": "Малина",
        "calories_per_100g": 52,
        "protein_per_100g": 1.2,
        "fat_per_100g": 0.7,
        "carbs_per_100g": 12.0,
        "fiber_per_100g": 6.5,
        "category": "fruits",
        "serving_size_g": 100,
    },

    # ========================================================================
    # LEGUMES (Бобовые)
    # ========================================================================
    {
        "name": "Lentils (dry)",
        "name_ru": "Чечевица (сухая)",
        "calories_per_100g": 352,
        "protein_per_100g": 25.0,
        "fat_per_100g": 1.1,
        "carbs_per_100g": 60.0,
        "fiber_per_100g": 11.0,
        "category": "legumes",
        "serving_size_g": 80,
    },
    {
        "name": "Chickpeas (dry)",
        "name_ru": "Нут (сухой)",
        "calories_per_100g": 364,
        "protein_per_100g": 19.0,
        "fat_per_100g": 6.0,
        "carbs_per_100g": 61.0,
        "fiber_per_100g": 17.4,
        "category": "legumes",
        "serving_size_g": 80,
    },
    {
        "name": "Black Beans (dry)",
        "name_ru": "Чёрная фасоль (сухая)",
        "calories_per_100g": 341,
        "protein_per_100g": 21.6,
        "fat_per_100g": 1.4,
        "carbs_per_100g": 62.0,
        "fiber_per_100g": 15.5,
        "category": "legumes",
        "serving_size_g": 80,
    },
    {
        "name": "Green Peas",
        "name_ru": "Зелёный горошек",
        "calories_per_100g": 81,
        "protein_per_100g": 5.4,
        "fat_per_100g": 0.4,
        "carbs_per_100g": 14.5,
        "fiber_per_100g": 5.7,
        "category": "legumes",
        "serving_size_g": 100,
    },
    {
        "name": "Kidney Beans (dry)",
        "name_ru": "Красная фасоль (сухая)",
        "calories_per_100g": 333,
        "protein_per_100g": 23.6,
        "fat_per_100g": 0.8,
        "carbs_per_100g": 60.0,
        "fiber_per_100g": 24.9,
        "category": "legumes",
        "serving_size_g": 80,
    },

    # ========================================================================
    # NUTS & SEEDS (Орехи и семена)
    # ========================================================================
    {
        "name": "Peanuts",
        "name_ru": "Арахис",
        "calories_per_100g": 567,
        "protein_per_100g": 25.8,
        "fat_per_100g": 49.2,
        "carbs_per_100g": 16.0,
        "fiber_per_100g": 8.5,
        "category": "nuts",
        "serving_size_g": 30,
    },
    {
        "name": "Almonds",
        "name_ru": "Миндаль",
        "calories_per_100g": 579,
        "protein_per_100g": 21.2,
        "fat_per_100g": 49.9,
        "carbs_per_100g": 22.0,
        "fiber_per_100g": 12.5,
        "category": "nuts",
        "serving_size_g": 30,
    },
    {
        "name": "Walnuts",
        "name_ru": "Грецкие орехи",
        "calories_per_100g": 654,
        "protein_per_100g": 15.2,
        "fat_per_100g": 65.2,
        "carbs_per_100g": 14.0,
        "fiber_per_100g": 6.7,
        "category": "nuts",
        "serving_size_g": 30,
    },
    {
        "name": "Cashews",
        "name_ru": "Кешью",
        "calories_per_100g": 553,
        "protein_per_100g": 18.2,
        "fat_per_100g": 43.9,
        "carbs_per_100g": 30.0,
        "fiber_per_100g": 3.3,
        "category": "nuts",
        "serving_size_g": 30,
    },
    {
        "name": "Sunflower Seeds",
        "name_ru": "Семена подсолнуха",
        "calories_per_100g": 584,
        "protein_per_100g": 20.8,
        "fat_per_100g": 51.5,
        "carbs_per_100g": 20.0,
        "fiber_per_100g": 8.6,
        "category": "nuts",
        "serving_size_g": 30,
    },
    {
        "name": "Chia Seeds",
        "name_ru": "Семена чиа",
        "calories_per_100g": 486,
        "protein_per_100g": 16.5,
        "fat_per_100g": 30.7,
        "carbs_per_100g": 42.0,
        "fiber_per_100g": 34.4,
        "category": "nuts",
        "serving_size_g": 15,
    },
    {
        "name": "Flax Seeds",
        "name_ru": "Семена льна",
        "calories_per_100g": 534,
        "protein_per_100g": 18.3,
        "fat_per_100g": 42.2,
        "carbs_per_100g": 29.0,
        "fiber_per_100g": 27.3,
        "category": "nuts",
        "serving_size_g": 15,
    },
    {
        "name": "Peanut Butter",
        "name_ru": "Арахисовая паста",
        "calories_per_100g": 588,
        "protein_per_100g": 25.0,
        "fat_per_100g": 50.0,
        "carbs_per_100g": 20.0,
        "fiber_per_100g": 6.0,
        "category": "nuts",
        "serving_size_g": 30,
    },

    # ========================================================================
    # PLANT-BASED PROTEIN (Растительный белок)
    # ========================================================================
    {
        "name": "Tofu",
        "name_ru": "Тофу",
        "calories_per_100g": 76,
        "protein_per_100g": 8.0,
        "fat_per_100g": 4.8,
        "carbs_per_100g": 1.9,
        "fiber_per_100g": 0.3,
        "category": "plant_protein",
        "serving_size_g": 150,
    },
    {
        "name": "Tempeh",
        "name_ru": "Темпе",
        "calories_per_100g": 192,
        "protein_per_100g": 20.3,
        "fat_per_100g": 10.8,
        "carbs_per_100g": 7.6,
        "fiber_per_100g": 0.0,
        "category": "plant_protein",
        "serving_size_g": 100,
    },

    # ========================================================================
    # OILS & FATS (Масла и жиры)
    # ========================================================================
    {
        "name": "Olive Oil",
        "name_ru": "Оливковое масло",
        "calories_per_100g": 884,
        "protein_per_100g": 0.0,
        "fat_per_100g": 100.0,
        "carbs_per_100g": 0.0,
        "fiber_per_100g": 0.0,
        "category": "oils",
        "serving_size_g": 15,
    },
    {
        "name": "Coconut Oil",
        "name_ru": "Кокосовое масло",
        "calories_per_100g": 862,
        "protein_per_100g": 0.0,
        "fat_per_100g": 100.0,
        "carbs_per_100g": 0.0,
        "fiber_per_100g": 0.0,
        "category": "oils",
        "serving_size_g": 15,
    },
    {
        "name": "Sunflower Oil",
        "name_ru": "Подсолнечное масло",
        "calories_per_100g": 884,
        "protein_per_100g": 0.0,
        "fat_per_100g": 100.0,
        "carbs_per_100g": 0.0,
        "fiber_per_100g": 0.0,
        "category": "oils",
        "serving_size_g": 15,
    },

    # ========================================================================
    # SWEETS & SNACKS (Сладости и снеки)
    # ========================================================================
    {
        "name": "Honey",
        "name_ru": "Мёд",
        "calories_per_100g": 304,
        "protein_per_100g": 0.3,
        "fat_per_100g": 0.0,
        "carbs_per_100g": 82.0,
        "fiber_per_100g": 0.2,
        "category": "sweets",
        "serving_size_g": 20,
    },
    {
        "name": "Dark Chocolate (70%)",
        "name_ru": "Тёмный шоколад (70%)",
        "calories_per_100g": 598,
        "protein_per_100g": 7.8,
        "fat_per_100g": 42.6,
        "carbs_per_100g": 46.0,
        "fiber_per_100g": 10.9,
        "category": "sweets",
        "serving_size_g": 25,
    },
    {
        "name": "Sugar",
        "name_ru": "Сахар",
        "calories_per_100g": 387,
        "protein_per_100g": 0.0,
        "fat_per_100g": 0.0,
        "carbs_per_100g": 100.0,
        "fiber_per_100g": 0.0,
        "category": "sweets",
        "serving_size_g": 10,
    },
    {
        "name": "Jam",
        "name_ru": "Варенье",
        "calories_per_100g": 278,
        "protein_per_100g": 0.4,
        "fat_per_100g": 0.1,
        "carbs_per_100g": 69.0,
        "fiber_per_100g": 1.1,
        "category": "sweets",
        "serving_size_g": 20,
    },
    {
        "name": "Dried Dates",
        "name_ru": "Финики сушёные",
        "calories_per_100g": 277,
        "protein_per_100g": 1.8,
        "fat_per_100g": 0.2,
        "carbs_per_100g": 75.0,
        "fiber_per_100g": 6.7,
        "category": "sweets",
        "serving_size_g": 40,
    },
    {
        "name": "Raisins",
        "name_ru": "Изюм",
        "calories_per_100g": 299,
        "protein_per_100g": 3.1,
        "fat_per_100g": 0.5,
        "carbs_per_100g": 79.0,
        "fiber_per_100g": 3.7,
        "category": "sweets",
        "serving_size_g": 30,
    },

    # ========================================================================
    # SUPPLEMENTS & SPORTS NUTRITION (Спортивное питание)
    # ========================================================================
    {
        "name": "Whey Protein Shake",
        "name_ru": "Протеиновый коктейль (сывороточный)",
        "calories_per_100g": 375,
        "protein_per_100g": 75.0,
        "fat_per_100g": 3.0,
        "carbs_per_100g": 10.0,
        "fiber_per_100g": 0.0,
        "category": "supplements",
        "serving_size_g": 30,
    },
    {
        "name": "Casein Protein",
        "name_ru": "Казеиновый протеин",
        "calories_per_100g": 370,
        "protein_per_100g": 72.0,
        "fat_per_100g": 3.5,
        "carbs_per_100g": 12.0,
        "fiber_per_100g": 0.0,
        "category": "supplements",
        "serving_size_g": 30,
    },
    {
        "name": "Protein Bar",
        "name_ru": "Протеиновый батончик",
        "calories_per_100g": 350,
        "protein_per_100g": 30.0,
        "fat_per_100g": 10.0,
        "carbs_per_100g": 35.0,
        "fiber_per_100g": 5.0,
        "category": "supplements",
        "serving_size_g": 60,
    },

    # ========================================================================
    # BEVERAGES & MISC (Напитки и прочее)
    # ========================================================================
    {
        "name": "Orange Juice",
        "name_ru": "Апельсиновый сок",
        "calories_per_100g": 45,
        "protein_per_100g": 0.7,
        "fat_per_100g": 0.2,
        "carbs_per_100g": 10.4,
        "fiber_per_100g": 0.2,
        "category": "beverages",
        "serving_size_g": 250,
    },
    {
        "name": "Coconut Milk",
        "name_ru": "Кокосовое молоко",
        "calories_per_100g": 230,
        "protein_per_100g": 2.3,
        "fat_per_100g": 23.8,
        "carbs_per_100g": 5.5,
        "fiber_per_100g": 2.2,
        "category": "beverages",
        "serving_size_g": 100,
    },
    {
        "name": "Soy Milk",
        "name_ru": "Соевое молоко",
        "calories_per_100g": 54,
        "protein_per_100g": 3.3,
        "fat_per_100g": 1.8,
        "carbs_per_100g": 6.3,
        "fiber_per_100g": 0.6,
        "category": "beverages",
        "serving_size_g": 250,
    },

    # ========================================================================
    # CONDIMENTS & SAUCES (Соусы и приправы)
    # ========================================================================
    {
        "name": "Mayonnaise",
        "name_ru": "Майонез",
        "calories_per_100g": 680,
        "protein_per_100g": 1.0,
        "fat_per_100g": 75.0,
        "carbs_per_100g": 0.6,
        "fiber_per_100g": 0.0,
        "category": "condiments",
        "serving_size_g": 15,
    },
    {
        "name": "Ketchup",
        "name_ru": "Кетчуп",
        "calories_per_100g": 112,
        "protein_per_100g": 1.7,
        "fat_per_100g": 0.1,
        "carbs_per_100g": 26.0,
        "fiber_per_100g": 0.3,
        "category": "condiments",
        "serving_size_g": 15,
    },
    {
        "name": "Soy Sauce",
        "name_ru": "Соевый соус",
        "calories_per_100g": 53,
        "protein_per_100g": 5.6,
        "fat_per_100g": 0.1,
        "carbs_per_100g": 6.7,
        "fiber_per_100g": 0.8,
        "category": "condiments",
        "serving_size_g": 15,
    },

    # ========================================================================
    # ADDITIONAL COMMON ITEMS (Дополнительные продукты)
    # ========================================================================
    {
        "name": "White Rice (cooked)",
        "name_ru": "Белый рис (варёный)",
        "calories_per_100g": 130,
        "protein_per_100g": 2.7,
        "fat_per_100g": 0.3,
        "carbs_per_100g": 28.0,
        "fiber_per_100g": 0.4,
        "category": "grains",
        "serving_size_g": 200,
    },
    {
        "name": "Buckwheat (cooked)",
        "name_ru": "Гречка (варёная)",
        "calories_per_100g": 110,
        "protein_per_100g": 4.2,
        "fat_per_100g": 1.1,
        "carbs_per_100g": 21.0,
        "fiber_per_100g": 2.7,
        "category": "grains",
        "serving_size_g": 200,
    },
    {
        "name": "Oatmeal (cooked)",
        "name_ru": "Овсяная каша (на воде)",
        "calories_per_100g": 68,
        "protein_per_100g": 2.5,
        "fat_per_100g": 1.4,
        "carbs_per_100g": 12.0,
        "fiber_per_100g": 1.7,
        "category": "grains",
        "serving_size_g": 300,
    },
    {
        "name": "Pasta (cooked)",
        "name_ru": "Макароны (варёные)",
        "calories_per_100g": 131,
        "protein_per_100g": 5.0,
        "fat_per_100g": 1.1,
        "carbs_per_100g": 25.0,
        "fiber_per_100g": 1.8,
        "category": "grains",
        "serving_size_g": 200,
    },
    {
        "name": "Whole Wheat Bread",
        "name_ru": "Цельнозерновой хлеб",
        "calories_per_100g": 247,
        "protein_per_100g": 13.0,
        "fat_per_100g": 3.4,
        "carbs_per_100g": 41.0,
        "fiber_per_100g": 7.0,
        "category": "grains",
        "serving_size_g": 30,
    },
    {
        "name": "Granola",
        "name_ru": "Гранола",
        "calories_per_100g": 471,
        "protein_per_100g": 10.0,
        "fat_per_100g": 20.0,
        "carbs_per_100g": 64.0,
        "fiber_per_100g": 7.0,
        "category": "grains",
        "serving_size_g": 50,
    },
    {
        "name": "Dried Apricots",
        "name_ru": "Курага",
        "calories_per_100g": 241,
        "protein_per_100g": 3.4,
        "fat_per_100g": 0.5,
        "carbs_per_100g": 63.0,
        "fiber_per_100g": 7.3,
        "category": "fruits",
        "serving_size_g": 40,
    },
    {
        "name": "Prunes",
        "name_ru": "Чернослив",
        "calories_per_100g": 240,
        "protein_per_100g": 2.2,
        "fat_per_100g": 0.4,
        "carbs_per_100g": 64.0,
        "fiber_per_100g": 7.1,
        "category": "fruits",
        "serving_size_g": 40,
    },
    {
        "name": "Hummus",
        "name_ru": "Хумус",
        "calories_per_100g": 166,
        "protein_per_100g": 7.9,
        "fat_per_100g": 9.6,
        "carbs_per_100g": 14.3,
        "fiber_per_100g": 6.0,
        "category": "legumes",
        "serving_size_g": 30,
    },
    {
        "name": "Ricotta",
        "name_ru": "Рикотта",
        "calories_per_100g": 174,
        "protein_per_100g": 11.3,
        "fat_per_100g": 13.0,
        "carbs_per_100g": 3.0,
        "fiber_per_100g": 0.0,
        "category": "dairy",
        "serving_size_g": 50,
    },
    {
        "name": "Feta Cheese",
        "name_ru": "Сыр фета",
        "calories_per_100g": 264,
        "protein_per_100g": 14.2,
        "fat_per_100g": 21.3,
        "carbs_per_100g": 4.1,
        "fiber_per_100g": 0.0,
        "category": "dairy",
        "serving_size_g": 30,
    },
    {
        "name": "Cheddar Cheese",
        "name_ru": "Сыр чеддер",
        "calories_per_100g": 403,
        "protein_per_100g": 25.0,
        "fat_per_100g": 33.0,
        "carbs_per_100g": 1.3,
        "fiber_per_100g": 0.0,
        "category": "dairy",
        "serving_size_g": 30,
    },
]
